openrouter_api_key ="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"
supabase_url = "https://pkicjdcisyvkbkrrprdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWNqZGNpc3l2a2JrcnJwcmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTQsImV4cCI6MjA2OTIxNjgxNH0.XXGlA_t7cQVDHtpJJvQEoxTxjpVzO_zMv7qyXlEVPFg"








