openrouter_api_key ="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"
supabase_url = "https://pkicjdcisyvkbkrrprdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWNqZGNpc3l2a2JrcnJwcmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTQsImV4cCI6MjA2OTIxNjgxNH0.XXGlA_t7cQVDHtpJJvQEoxTxjpVzO_zMv7qyXlEVPFg"





