openrouter_api_key ="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"
supabase_url = "https://pkicjdcisyvkbkrrprdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWNqZGNpc3l2a2JrcnJwcmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTQsImV4cCI6MjA2OTIxNjgxNH0.XXGlA_t7cQVDHtpJJvQEoxTxjpVzO_zMv7qyXlEVPFg"






