openrouter_api_key ="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"
supabase_url = "https://pkicjdcisyvkbkrrprdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWNqZGNpc3l2a2JrcnJwcmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTQsImV4cCI6MjA2OTIxNjgxNH0.XXGlA_t7cQVDHtpJJvQEoxTxjpVzO_zMv7qyXlEVPFg"







